name: quality

on:
  workflow_call:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  changes:
    runs-on: [self-hosted, linux, x64, netcup, general]
    permissions:
      pull-requests: read
    outputs:
      lua: ${{ steps.changes.outputs.lua }}
      markdown: ${{ steps.changes.outputs.markdown }}
      vimdoc: ${{ steps.changes.outputs.vimdoc }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          working-directory: repo
          filters: |
            lua:
              - 'lua/**'
              - 'plugin/**'
              - 'spec/**'
              - '*.lua'
              - '.luarc.json'
              - '*.toml'
              - 'vim.yaml'
            markdown:
              - '*.md'
            vimdoc:
              - 'doc/**'

  lua-format:
    name: Lua Format Check
    runs-on: [self-hosted, linux, x64, netcup, general]
    needs: changes
    if: ${{ needs.changes.outputs.lua == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command stylua --check .
        working-directory: repo

  lua-lint:
    name: Lua Lint Check
    runs-on: [self-hosted, linux, x64, netcup, general]
    needs: changes
    if: ${{ needs.changes.outputs.lua == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command selene --display-style quiet .
        working-directory: repo

  lua-typecheck:
    name: Lua Type Check
    runs-on: [self-hosted, linux, x64, netcup, general]
    needs: changes
    if: ${{ needs.changes.outputs.lua == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo
      - uses: actions/checkout@v4
        with:
          path: repo
      - uses: actions/checkout@v4
        with:
          repository: barrettruth/canola.nvim
          ref: canola
          path: repo/_canola
      - uses: stevearc/nvim-typecheck-action@v2
        with:
          path: repo/lua
          luals-version: 3.16.4
          libraries: ${{ github.workspace }}/repo/_canola/lua

  vimdoc-check:
    name: Vimdoc Check
    runs-on: [self-hosted, linux, x64, netcup, general]
    needs: changes
    if: ${{ needs.changes.outputs.vimdoc == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo
      - uses: cachix/install-nix-action@v31
      - run:
          nix develop --command vimdoc-language-server check doc/
          --no-runtime-tags
        working-directory: repo

  markdown-format:
    name: Markdown Format Check
    runs-on: [self-hosted, linux, x64, netcup, general]
    needs: changes
    if: ${{ needs.changes.outputs.markdown == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: repo
      - uses: cachix/install-nix-action@v31
      - run: nix develop --command prettier --check .
        working-directory: repo
